// Dev tool: convert snarkjs vk/proof/public into the verifier's Rust testdata
// module, using the @zk-pob/zk BN254 encoder (single source for serialization).
// Run from packages/zk after a fullprove (see the "gen:testdata" npm script).
import { readFileSync, writeFileSync } from "node:fs";
import { encodeVk, encodeProof, encodePublicSignals } from "@zk-pob/zk";

const vk = JSON.parse(readFileSync("build/verification_key.json", "utf8"));
const proof = JSON.parse(readFileSync("proof.json", "utf8"));
const pub = JSON.parse(readFileSync("public.json", "utf8"));

const evk = encodeVk(vk);
const eproof = encodeProof(proof);
const esignals = encodePublicSignals(pub);

if (esignals.length !== 6) throw new Error(`expected 6 public signals, got ${esignals.length}`);
if (evk.ic.length !== 7) throw new Error(`expected 7 IC points, got ${evk.ic.length}`);

const arr = (u8) => `[${Array.from(u8).join(", ")}]`;
const nested = (list, n) =>
  `[\n${list.map((u8) => `    ${arr(u8)}`).join(",\n")}\n]`;

const out = `// @generated by packages/zk/gentestdata.tmp.mjs — do not edit by hand.
// Real Groth16 proof + verification key for the proof_of_backing circuit,
// serialized to BN254 host-function bytes. Used to exercise the on-chain
// pairing check under \`cargo test\` (the BN254 host fns run in the test host).
#![allow(clippy::all)]

pub const VK_ALPHA1: [u8; 64] = ${arr(evk.alpha1)};
pub const VK_BETA2: [u8; 128] = ${arr(evk.beta2)};
pub const VK_GAMMA2: [u8; 128] = ${arr(evk.gamma2)};
pub const VK_DELTA2: [u8; 128] = ${arr(evk.delta2)};
pub const VK_IC: [[u8; 64]; 7] = ${nested(evk.ic)};

pub const PROOF_A: [u8; 64] = ${arr(eproof.a)};
pub const PROOF_B: [u8; 128] = ${arr(eproof.b)};
pub const PROOF_C: [u8; 64] = ${arr(eproof.c)};

pub const PUBLIC: [[u8; 32]; 6] = ${nested(esignals)};
`;

writeFileSync("../contracts/verifier/src/testdata.rs", out);
console.log("wrote packages/contracts/verifier/src/testdata.rs");
