#!/usr/bin/env bash
#
# OPS-2 — Deploy + initialize one (token, verifier) pair per project on Stellar
# testnet (DEC-1 = a: one deploy per project). Steps:
#   1. build contracts + the TS workspaces this script needs
#   2. deploy token + verifier
#   3. token.init(admin) + set_supply(SUPPLY)
#   4. verifier.init(admin, token, token_id_felt, vk)   (vk = ZK-5 artifact)
#   5. verifier.allow_attestor(ax||ay)                  (attestor pubkey)
#   6. write scripts/.deploy/deployed.json + update .env ids (consumed by api/web)
#
# Env (override as needed):
#   STELLAR_SOURCE   funded testnet identity in `stellar keys`   (default: deployer)
#   STELLAR_NETWORK  network passphrase alias                    (default: testnet)
#   SUPPLY           token total_supply to set                   (default: 1000000)
#   TOKEN_ID_FELT    tokenId field element bound in the sig msg  (default: 424242)
#   ATTESTOR_PRIVATE_KEY  hex BabyJubjub key; generated + saved to .env if unset
#
set -euo pipefail
cd "$(dirname "$0")"
ROOT="$(cd .. && pwd)"
OUT=".deploy"
mkdir -p "$OUT"

NETWORK="${STELLAR_NETWORK:-testnet}"
SOURCE="${STELLAR_SOURCE:-deployer}"
SUPPLY="${SUPPLY:-1000000}"
TOKEN_ID_FELT="${TOKEN_ID_FELT:-424242}"

command -v stellar >/dev/null || { echo "stellar CLI not found"; exit 1; }

# Load .env (ATTESTOR_PRIVATE_KEY, etc.) without clobbering already-set vars.
if [ -f "$ROOT/.env" ]; then set -a; . "$ROOT/.env"; set +a; fi

ADMIN=$(stellar keys address "$SOURCE")
echo "==> source identity: $SOURCE ($ADMIN) on $NETWORK"

echo "==> building TS workspaces (shared, zk, attestor) + exporting vk"
( cd "$ROOT" && npm run --silent build --workspace packages/shared --workspace packages/zk --workspace apps/attestor )
( cd "$ROOT/packages/zk" && node exportvk.mjs )
VK_JSON="$ROOT/packages/zk/build/vk.contract.json"
[ -f "$VK_JSON" ] || { echo "missing $VK_JSON (run circuit build first)"; exit 1; }

# tokenId felt -> 32-byte big-endian hex (single-sourced via the @zk-pob/zk encoder).
TOKEN_ID_FELT_HEX=$(cd "$ROOT/packages/zk" && node -e \
  'import("@zk-pob/zk").then(z=>process.stdout.write(z.bytesToHex(z.feltTo32BE(process.argv[1]))))' \
  "$TOKEN_ID_FELT")

# Ensure an attestor key exists; derive its on-chain allowlist key (ax||ay).
if [ -z "${ATTESTOR_PRIVATE_KEY:-}" ]; then
  ATTESTOR_PRIVATE_KEY=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')
  printf '\n# Demo attestor BabyJubjub key, generated by deploy.sh (testnet only).\nATTESTOR_PRIVATE_KEY=%s\n' \
    "$ATTESTOR_PRIVATE_KEY" >> "$ROOT/.env"
  export ATTESTOR_PRIVATE_KEY
  echo "==> generated a demo attestor key, saved to .env"
fi
ALLOWLIST_KEY=$(ATTESTOR_PRIVATE_KEY="$ATTESTOR_PRIVATE_KEY" node "$ROOT/apps/attestor/dist/cli.js" pubkey)

echo "==> building contracts"
stellar contract build --manifest-path "$ROOT/packages/contracts/token/Cargo.toml"
stellar contract build --manifest-path "$ROOT/packages/contracts/verifier/Cargo.toml"

# stellar CLI's wasm target dir changed across versions (wasm32v1-none on 25.x,
# wasm32-unknown-unknown earlier). Resolve it instead of hardcoding.
find_wasm() {
  find "$ROOT/target" -name "$1" -path "*release*" -not -path "*/deps/*" 2>/dev/null | head -1
}
TOKEN_WASM=$(find_wasm zk_pob_token.wasm)
VERIFIER_WASM=$(find_wasm zk_pob_verifier.wasm)
[ -n "$TOKEN_WASM" ] && [ -n "$VERIFIER_WASM" ] || { echo "wasm not found under target/"; exit 1; }

echo "==> deploying token"
TOKEN_ID=$(stellar contract deploy --wasm "$TOKEN_WASM" --source "$SOURCE" --network "$NETWORK")
echo "==> deploying verifier"
VERIFIER_ID=$(stellar contract deploy --wasm "$VERIFIER_WASM" --source "$SOURCE" --network "$NETWORK")
echo "token:    $TOKEN_ID"
echo "verifier: $VERIFIER_ID"

invoke() { # contract_id, then -- fn args...
  local id="$1"; shift
  stellar contract invoke --id "$id" --source "$SOURCE" --network "$NETWORK" "$@"
}

echo "==> token.init + set_supply($SUPPLY)"
invoke "$TOKEN_ID" -- init --admin "$ADMIN"
invoke "$TOKEN_ID" -- set_supply --amount "$SUPPLY"

echo "==> verifier.init (token=$TOKEN_ID, token_id_felt=$TOKEN_ID_FELT)"
invoke "$VERIFIER_ID" -- init \
  --admin "$ADMIN" \
  --token "$TOKEN_ID" \
  --token_id_felt "$TOKEN_ID_FELT_HEX" \
  --vk "$(cat "$VK_JSON")"

echo "==> verifier.allow_attestor"
invoke "$VERIFIER_ID" -- allow_attestor --key "$ALLOWLIST_KEY"

# --- persist results ---
cat > "$OUT/deployed.json" <<JSON
{
  "network": "$NETWORK",
  "tokenId": "$TOKEN_ID",
  "verifierId": "$VERIFIER_ID",
  "tokenIdFelt": "$TOKEN_ID_FELT",
  "supply": "$SUPPLY",
  "attestorAllowlistKey": "$ALLOWLIST_KEY"
}
JSON
echo "==> wrote $OUT/deployed.json"

# Upsert ids into .env so apps/api (VERIFIER_ID/TOKEN_ID) and apps/web
# (NEXT_PUBLIC_*) pick up the live deployment.
set_env() { # key value
  local k="$1" v="$2" f="$ROOT/.env"
  touch "$f"
  if grep -q "^$k=" "$f"; then
    local tmp; tmp=$(mktemp); sed "s|^$k=.*|$k=$v|" "$f" > "$tmp" && mv "$tmp" "$f"
  else
    printf '%s=%s\n' "$k" "$v" >> "$f"
  fi
}
set_env TOKEN_ID "$TOKEN_ID"
set_env VERIFIER_ID "$VERIFIER_ID"
set_env NEXT_PUBLIC_TOKEN_ID "$TOKEN_ID"
set_env NEXT_PUBLIC_VERIFIER_ID "$VERIFIER_ID"
echo "==> updated .env ids"
echo "==> done. next: ./e2e.sh (attest -> prove -> verify, happy + tamper)"
